### ISSUE TITLE
CSV downloads missing rows and contains an error

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#3489]
## Due date:
June 2nd

## Description:

A datastore query using the CSV download endpoint is producing a 500 server error at row 3000 of the results. We think the error from watchdog that corresponds to it is this one:

```
Notice: ob_flush(): failed to flush buffer. No buffer to flush in Drupal\datastore\Controller\QueryController->sendRows() (line 199 of /mnt/www/html/openpaymentsstg/docroot/modules/contrib/dkan/modules/datastore/src/Controller/QueryController.php)
#0 /mnt/www/html/openpaymentsstg/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'ob_flush(): fai...', '/mnt/www/html/o...', 199, Array)
#1 [internal function]: _drupal_error_handler(8, 'ob_flush(): fai...', '/mnt/www/html/o...', 199, Array)
#2 /mnt/www/html/openpaymentsstg/docroot/modules/contrib/dkan/modules/datastore/src/Controller/QueryController.php(199): ob_flush()
#3 /mnt/www/html/openpaymentsstg/docroot/modules/contrib/dkan/modules/datastore/src/Controller/QueryController.php(164): Drupal\datastore\Controller\QueryController->sendRows(Resource id #17, Array)
#4 /mnt/www/html/openpaymentsstg/vendor/symfony/http-foundation/StreamedResponse.php(114): Drupal\datastore\Controller\QueryController->Drupal\datastore\Controller\{closure}()
#5 /mnt/www/html/openpaymentsstg/vendor/symfony/http-foundation/Response.php(374): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#6 /mnt/www/html/openpaymentsstg/docroot/index.php(20): Symfony\Component\HttpFoundation\Response->send()
#7 {main}
```

## Acceptance Criteria: 
CSV file should contain all rows and no errors. Following the pattern of the data sets downloads. 

## Estimate: 
1 day

**Comment by ghost** [comment]
Nikolay and Dan will pair on this.

**Comment by dafeder** [comment]
We're seeing this happen at different places in the streaming CSV response, sometimes at 3k rows sometimes much later. On Acquia this seems to be the corresponding Apache error log item:

```
[Fri May 28 15:37:49 2021] [error] [pid=22159] 209.95.136.192 "http://xxxxxxxxx.prod.acquia-sites.com/company/100000000329" "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" vhost=xxxxxxxxx.prod.acquia-sites.com forwarded_for="209.95.136.192" request_id="v-17b614ca-bfc9-11eb-93e4-53bdc3924e65" hosting_site=openpaymentsstg FastCGI: comm with server "/var/www/site-fpm/xxxxxxxxx.test/php-fpm" aborted: read failed
[Fri May 28 15:37:49 2021] [error] [pid=22159] 209.95.136.192 "http://xxxxxxxxxxxxxx.prod.acquia-sites.com/company/100000000329" "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" vhost=xxxxxxxxx.prod.acquia-sites.com forwarded_for="209.95.136.192" request_id="v-17b614ca-bfc9-11eb-93e4-53bdc3924e65" hosting_site=xxxxxxxxx AH00524: Handler for fastcgi-script returned invalid result code 1
```

Currently importing the 5gig CVS file locally in my docker environment to see if I can reproduce.

**Comment by akaroleff** [comment]
We believe this will be an Acquia side issue 
Dan put in an Acquia ticket that is prioritized as high with a completion date requested

**Comment by dafeder** [comment]
There doesn't seem to be any issue we can fix here at the application/code level, we need to be adding indexing to large tables to avoid errors resulting from very long wait times, will address at the site level or create a new ticket for adding indexes after import (probably as part of data dictionaries).
