### ISSUE TITLE
User Warning flooding the logs when creating or updating datasets

### ISSUE THREAD

**Issue by neuronick** [GetDKAN/dkan#3547]
Whenever a dataset is created or updated, an error related to `htmlpurifier` shows up in the log:
```
User warning: Directory /vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 775 in HTMLPurifier_DefinitionCache_Serializer->_testPermissions() (line 297 of /vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php) #0 /docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(512, 'Directory /mnt/...', '/mnt/www/html/d...', 297, Array)
#1 [internal function]: _drupal_error_handler(512, 'Directory /mnt/...', '/mnt/www/html/d...', 297, Array)
#2 /vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php(297): trigger_error('Directory /mnt/...', 512)
#3 /vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php(238): HTMLPurifier_DefinitionCache_Serializer->_testPermissions('/mnt/www/html/d...', 509)
#4 /vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php(125): HTMLPurifier_DefinitionCache_Serializer->_prepareDir(Object(HTMLPurifier_Config))
#5 /vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Decorator.php(108): HTMLPurifier_DefinitionCache_Serializer->cleanup(Object(HTMLPurifier_Config))
#6 /vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Decorator/Cleanup.php(31): HTMLPurifier_DefinitionCache_Decorator->cleanup(Object(HTMLPurifier_Config))
#7 /vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(518): HTMLPurifier_DefinitionCache_Decorator_Cleanup->add(Object(HTMLPurifier_HTMLDefinition), Object(HTMLPurifier_Config))
#8 /vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(415): HTMLPurifier_Config->getDefinition('HTML', false, false)
#9 /vendor/ezyang/htmlpurifier/library/HTMLPurifier/Generator.php(74): HTMLPurifier_Config->getHTMLDefinition()
#10 /vendor/ezyang/htmlpurifier/library/HTMLPurifier.php(158): HTMLPurifier_Generator->__construct(Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#11 /docroot/modules/contrib/dkan/modules/metastore/src/Storage/Data.php(376): HTMLPurifier->purify('9c423a43f0c4800...')
#12 /docroot/modules/contrib/dkan/modules/metastore/src/Storage/Data.php(346): Drupal\metastore\Storage\Data->htmlPurifier('9c423a43f0c4800...')
#13 /docroot/modules/contrib/dkan/modules/metastore/src/Storage/Data.php(351): Drupal\metastore\Storage\Data->filterHtml('9c423a43f0c4800...')
#14 /docroot/modules/contrib/dkan/modules/metastore/src/Storage/Data.php(351): Drupal\metastore\Storage\Data->filterHtml(Object(stdClass))
#15 /docroot/modules/contrib/dkan/modules/metastore/src/Storage/Data.php(270): Drupal\metastore\Storage\Data->filterHtml(Object(stdClass))
#16 /docroot/modules/contrib/dkan/modules/metastore/src/Reference/Referencer.php(328): Drupal\metastore\Storage\Data->store(Object(stdClass), '98fd910f-c4aa-5...')
#17 /docroot/modules/contrib/dkan/modules/metastore/src/Reference/Referencer.php(119): Drupal\metastore\Reference\Referencer->createPropertyReference('distribution', Object(stdClass))
#18 /docroot/modules/contrib/dkan/modules/metastore/src/Reference/Referencer.php(92): Drupal\metastore\Reference\Referencer->referenceSingle('distribution', Object(stdClass))
#19 /docroot/modules/contrib/dkan/modules/metastore/src/Reference/Referencer.php(70): Drupal\metastore\Reference\Referencer->referenceMultiple('distribution', Array)
#20 /docroot/modules/contrib/dkan/modules/metastore/src/Reference/Referencer.php(51): Drupal\metastore\Reference\Referencer->referenceProperty('distribution', Array)
#21 /docroot/modules/contrib/dkan/modules/metastore/src/LifeCycle/LifeCycle.php(272): Drupal\metastore\Reference\Referencer->reference(Object(stdClass))
#22 /docroot/modules/contrib/dkan/modules/metastore/src/LifeCycle/LifeCycle.php(108): Drupal\metastore\LifeCycle\LifeCycle->datasetPresave(Object(Drupal\metastore\NodeWrapper\Data))
#23 /docroot/modules/contrib/dkan/modules/metastore/metastore.module(83): Drupal\metastore\LifeCycle\LifeCycle->go('Presave', Object(Drupal\metastore\NodeWrapper\Data))
#24 /docroot/modules/contrib/dkan/modules/metastore/metastore.module(28): metastore_data_lifecycle(Object(Drupal\node\Entity\Node), 'presave')
#25 [internal function]: metastore_entity_presave(Object(Drupal\node\Entity\Node))
#26 /docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('metastore_entit...', Array)
#27 /docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(206): Drupal\Core\Extension\ModuleHandler->invokeAll('entity_presave', Array)
#28 /docroot/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(843): Drupal\Core\Entity\EntityStorageBase->invokeHook('presave', Object(Drupal\node\Entity\Node))
#29 /docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(500): Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('presave', Object(Drupal\node\Entity\Node))
#30 /docroot/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(700): Drupal\Core\Entity\EntityStorageBase->doPreSave(Object(Drupal\node\Entity\Node))
#31 /docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(454): Drupal\Core\Entity\ContentEntityStorageBase->doPreSave(Object(Drupal\node\Entity\Node))
#32 /docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(837): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\node\Entity\Node))
#33 /docroot/core/lib/Drupal/Core/Entity/EntityBase.php(395): Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object(Drupal\node\Entity\Node))
#34 /docroot/core/modules/node/src/NodeForm.php(294): Drupal\Core\Entity\EntityBase->save()
#35 [internal function]: Drupal\node\NodeForm->save(Array, Object(Drupal\Core\Form\FormState))
#36 /docroot/core/lib/Drupal/Core/Form/FormSubmitter.php(114): call_user_func_array(Array, Array)
#37 /docroot/core/lib/Drupal/Core/Form/FormSubmitter.php(52): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\Core\Form\FormState))
#38 /docroot/core/lib/Drupal/Core/Form/FormBuilder.php(593): Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object(Drupal\Core\Form\FormState))
#39 /docroot/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm('node_data_form', Array, Object(Drupal\Core\Form\FormState))
#40 /docroot/core/lib/Drupal/Core/Controller/FormController.php(91): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\node\NodeForm), Object(Drupal\Core\Form\FormState))
#41 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#42 /docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#43 /docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#44 /docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#45 /docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#46 /vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#47 /vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#48 /docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#49 /docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#50 /docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#51 /docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#52 /vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(49): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#53 /docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#54 /docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#55 /vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#56 /docroot/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#57 /docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#58 {main}. request_id="v-06f3b22a-eef7-11eb-936a-3b8a5aa3d84c"
```

## Steps To Reproduce

1. Create or update a dataset.
2. View watchdog / dblog.

**Comment by neuronick** [comment]
For the moment I solved this via composer patch doing something like this:

```
diff --git a/modules/metastore/src/Storage/Data.php b/modules/metastore/src/Storage/Data.php
index 4a37cd16..8e57562c
--- a/modules/metastore/src/Storage/Data.php
+++ b/modules/metastore/src/Storage/Data.php
@@ -340,7 +340,11 @@ class Data implements StorerInterface, RetrieverInterface, BulkRetrieverInterfac
    * @codeCoverageIgnore
    */
   private function htmlPurifier(string $input) {
-    $filter = new \HTMLPurifier();
+    $purifier_config = \HTMLPurifier_Config::createDefault();
+    $temp = \Drupal::service('file_system')->getTempDirectory();
+    $purifier_config->set('Cache.SerializerPath', $temp);
+
+    $filter = new \HTMLPurifier($purifier_config);
     return $filter->purify($input);
   }

**Comment by dafeder** [comment]
Thank you @neuronick! I will create a PR, feel free to submit PRs directly in the future.
