### ISSUE TITLE
Encountering fatal error whenever running the `resource_purger` queue.

### ISSUE THREAD

**Issue by clayliddell** [GetDKAN/dkan#3572]
## Describe the bug

Whenever I attempt to run the `resource_purger` queue, I receive the following error:
```
TypeError: Argument 1 passed to Drupal\datastore\Service\ResourcePurger::delete() must be of the type string, null given, called in /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php on line 195 in Drupal\datastore\Service\ResourcePurger->delete() (line 319 of /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php) #0 /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(195): Drupal\datastore\Service\ResourcePurger->delete(NULL, NULL)
#1 /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(167): Drupal\datastore\Service\ResourcePurger->purge(31441, '63ce305b-b934-4...', false)
#2 /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(150): Drupal\datastore\Service\ResourcePurger->purgeHelper(31441, '63ce305b-b934-4...', false)
#3 /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Plugin/QueueWorker/ResourcePurgerWorker.php(52): Drupal\datastore\Service\ResourcePurger->purgeMultiple(Array, false)
#4 /mnt/www/html/datahealthcarestg/docroot/core/lib/Drupal/Core/Cron.php(180): Drupal\datastore\Plugin\QueueWorker\ResourcePurgerWorker->processItem(Array)
#5 /mnt/www/html/datahealthcarestg/docroot/core/lib/Drupal/Core/Cron.php(145): Drupal\Core\Cron->processQueues()
#6 /mnt/www/html/datahealthcarestg/docroot/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\Core\Cron->run()
#7 /mnt/www/html/datahealthcarestg/vendor/drush/drush/src/Drupal/Commands/core/DrupalCommands.php(76): Drupal\Core\ProxyClass\Cron->run()
#8 [internal function]: Drush\Drupal\Commands\core\DrupalCommands->cron(Array)
#9 /mnt/www/html/datahealthcarestg/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#10 /mnt/www/html/datahealthcarestg/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /mnt/www/html/datahealthcarestg/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /mnt/www/html/datahealthcarestg/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /mnt/www/html/datahealthcarestg/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /mnt/www/html/datahealthcarestg/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /mnt/www/html/datahealthcarestg/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /mnt/www/html/datahealthcarestg/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /mnt/www/html/datahealthcarestg/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /mnt/www/html/datahealthcarestg/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /mnt/www/html/datahealthcarestg/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#20 /mnt/www/html/datahealthcarestg/vendor/drush/drush/drush(4): require('/mnt/www/html/d...')
#21 {main}. 
TypeError: Argument 1 passed to Drupal\datastore\Service\ResourcePurger::delete() must be of the type string, null given, called in /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php on line 195 in Drupal\datastore\Service\ResourcePurger->delete() (line 319 of /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php).
```

This wouldn't be such a big deal if it wasn't for:
1. The queue item responsible for creating the above error appears to be re-queued on error.
2. If the queue items are processed using the `drush cron` command, the above error is fatal, and all subsequent queue items are never processed.

## Steps To Reproduce

1. Navigate to the Dataset Creation page (`/node/add/data`).
2. Fill out all of the required fields.
3. Fill out the distribution title field and the distribution format field, but not the Download URL field.
4. Save the dataset.
5. Edit the newly created dataset.
6. Provide a resource for the Download URL field.
7. Save the dataset.
8. Run the `resource_purger` queue.
9. Verify that you encountered the above error.

## Expected behavior

Running the `resource_purger` queue should not result in the above error.

**Comment by janette** [comment]
👉  https://github.com/GetDKAN/dkan/commit/d447357824aef9b691cb67b2d843a6866d642935
