### ISSUE TITLE
Handle missing resource when dropping a datastore

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#4340]
### Current Behavior

Error when running `drush dkan:datastore:drop` when the resource is missing
```
 TypeError: Drupal\datastore\Events\DatastoreEventBase::__construct(): Argument #1 ($data_resource) must be of type Drupal\common\DataResource, null given, called in /var/www/html/docroot/modules/contrib/dkan/modules/datastore/src/DatastoreService.php on line 275 in Drupal\datastore\Events\DatastoreEventBase->__construct() (line 26 of /var/www/html/docroot/modules/contrib/dkan/modules/datastore/src/Events/DatastoreEventBase.php) #0 /var/www/html/docroot/modules/contrib/dkan/modules/datastore/src/DatastoreService.php(275): Drupal\datastore\Events\DatastoreEventBase->__construct(NULL)
#1 /var/www/html/docroot/modules/contrib/dkan/modules/datastore/src/Drush.php(227): Drupal\datastore\DatastoreService->drop('4b8a081fe9af7c3...', NULL, true)
#2 [internal function]: Drupal\datastore\Drush->drop('4b8a081fe9af7c3...', Array)
#3 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#7 /var/www/html/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#14 /var/www/html/vendor/drush/drush/drush(4): require('/var/www/html/v...')
#15 /var/www/html/vendor/bin/drush(119): include('/var/www/html/v...')
#16 {main}.
```

### Expected Behavior

User should see a message that that no resource could be found.

### Steps To Reproduce

1. Run dkan:datastore:drop on a resource id
2. Run it a second time
3. Confirm you see the error above

**Comment by paul-m** [comment]
I ran into this where I used the Datasets admin form to delete a whole bunch of Data nodes, and then ran cron.

Added a PR to avoid the error, but it probably speaks more to some other area where subsystems are out of sync wrt deleted nodes.

**Comment by paul-m** [comment]
This is back after https://github.com/GetDKAN/dkan/pull/4351

**Comment by dafeder** [comment]
Hmm looks like we should have added a test in #4343?

**Comment by paul-m** [comment]
yupyup.
